### ISSUE TITLE
CRUD Operations Fail

### ISSUE THREAD

**Issue by rsomani95** [BekBrace/FARM-Stack-Course#2]
Hello, thank you for sharing this! I found this repo through your YouTube tutorial, which was very helpful to get started.

Currently, when trying any of the database related operations from the FastAPI docs, I always fail with a response code of 500 with an `Internal Server Error`. Here's the full stack trace:
```python
RuntimeError: Task <Task pending coro=<RequestResponseCycle.run_asgi() running at /Users/rahulsomani/miniconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py:376> cb=[set.discard()]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Users/rahulsomani/miniconda3/lib/python3.7/asyncio/futures.py:351]> attached to a different loop
```

I was able to resolve the issue following the advice in this [StackOverflow](https://stackoverflow.com/questions/65542103/future-task-attached-to-a-different-loop) post.

I changed `database.py` as follows:
```python
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase

DB_URL = "mongodb://127.0.0.1:27017/"

db: AsyncIOMotorDatabase = None


async def get_db_client() -> AsyncIOMotorClient:
    client = AsyncIOMotorClient(DB_URL)
    return client


async def get_db(name="TodoList") -> AsyncIOMotorDatabase:
    db = await get_db_client()
    return db[name]
```

Then load the db on startup in `main.py`:
```python
...

app = FastAPI()
app.add_event_handler("startup", get_db)
```

And had to add a line to all the functions inside `database.py` like so:
```python
async def remove_todo(id: int):
    db = await get_db()
    await db["todo"].delete_one({"id": id})
    return True

async def create_todo(todo):
    doc = todo
    db = await get_db()
    res = await db["todo"].insert_one(doc)
    return doc


...  # and so on
```

---

Is this the correct way to do things? I'm new to writing code with `async` and `await`, and was wondering if calling `db = await get_db()` inside all the functions that fetch / modify from the databse is inefficient? 

Thanks!

**Comment by nahuakang** [comment]
I haven't watched the video but your solution seems fine.

Getting an instance of `db` with the `await` keyword is not inefficient. It just means that it might take some time for the `db` to load so the system can do some other tasks in between. Think about it: All the endpoints you've created might have `async` signature, which means that FastAPI must `await` them. Is that inefficient? ;) 

Just a note that the `Sqlalchemy` + any relational DB code in the [official doc](https://fastapi.tiangolo.com/tutorial/sql-databases/) works out of the doc. I've never used `mongo` but the solution you found seems good enough.
